
from typing import List
from typing import cast

from unittest import TestSuite
from unittest import main as unitTestMain

from os import sep as osSep

from pathlib import Path

from random import choice

from umlmodel.Actor import Actor
from umlmodel.Class import Class
from umlmodel.Field import Field
from umlmodel.Method import Method
from umlmodel.Note import Note
from umlmodel.Parameter import Parameter
from umlmodel.ParameterType import ParameterType
from umlmodel.Text import Text
from umlmodel.UseCase import UseCase
from umlmodel.enumerations.Stereotype import Stereotype
from umlmodel.enumerations.Visibility import Visibility
from umlmodel.enumerations.DisplayParameters import DisplayParameters

from umlshapes.preferences.UmlPreferences import UmlPreferences

from umlshapes.shapes.UmlActor import UmlActor
from umlshapes.shapes.UmlClass import UmlClass
from umlshapes.shapes.UmlNote import UmlNote
from umlshapes.shapes.UmlText import UmlText
from umlshapes.shapes.UmlUseCase import UmlUseCase

from umlshapes.types.UmlDimensions import UmlDimensions
from umlshapes.types.UmlPosition import UmlPosition

from umlshapes.lib.ogl import OGLInitialize

from umlio.IOTypes import UmlDocument
from umlio.IOTypes import UmlDocumentType

from umlio.serializer.UmlShapesToXml import UmlShapesToXml

from tests.umlio.UmlIOBaseTest import UmlIOBaseTest

EXPECTED_EMPTY_PROJECT: str = '<?xml version=\'1.0\' encoding=\'iso-8859-1\'?>\n<UmlProject fileName="." version="14.0" codePath="/users/hasii" />'

EXPECTED_EMPTY_DIAGRAM: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n    '
    '<UMLDiagram documentType="Not Set" title="" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1" />\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_CLASS_XML: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n'
    '    <UMLDiagram documentType="Class Document" title="Unit Test Class Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlClass id="play.small.long.group" width="125" height="100" x="300" y="500">\n'
    '            <ModelClass id="0" name="ClassName1" displayMethods="True" displayParameters="Unspecified" displayConstructor="Unspecified" displayDunderMethods="Unspecified" displayFields="True" displayStereotype="True" fileName="" description="" />\n'
    '        </UmlClass>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_USE_CASE_XML: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n'
    '    <UMLDiagram documentType="Use Case Document" title="Use Case Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlUseCase id="remember.central.issue.child" width="125" height="100" x="300" y="500">\n'
    '            <ModelUseCase id="1" name="I am a lonely boy" fileName="" />\n'
    '        </UmlUseCase>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_ACTOR: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n'
    '    <UMLDiagram documentType="Use Case Document" title="Use Case Actor Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlActor id="remember.central.issue.child" width="233" height="233" x="500" y="200">\n'
    '            <ModelActor id="0" name="LoboMalo" fileName="" />\n'
    '        </UmlActor>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_NOTE: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n'
    '    <UMLDiagram documentType="Use Case Document" title="Uml Note Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlNote id="remember.the.Alamo" width="233" height="233" x="666" y="777">\n'
    '            <ModelNote id="777" content="I am the best MAGA Note" fileName="" />\n'
    '        </UmlNote>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_TEXT: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject fileName="." version="14.0" codePath="/users/hasii">\n'
    '    <UMLDiagram documentType="Class Document" title="Uml Text Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlText id="remember.the.Alamo" width="150" height="50" x="1024" y="768">\n'
    '            <ModelText id="1789" content="Soy el mejor texto americano" />\n'
    '        </UmlText>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)


class TestUmlShapesToXml(UmlIOBaseTest):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 19 June 2025
    """

    classCounter:     int  = 111
    methodCounter:    int  = 222
    parameterCounter: int  = 333
    fieldCounter:     int  = 444
    TEMPORARY_PATH:   Path = cast(Path, None)

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

        TestUmlShapesToXml.TEMPORARY_PATH = Path(f'{Path.home()}{osSep}tmp')
        if TestUmlShapesToXml.TEMPORARY_PATH.exists():
            TestUmlShapesToXml.deleteDirectory(path=TestUmlShapesToXml.TEMPORARY_PATH)
        TestUmlShapesToXml.TEMPORARY_PATH.mkdir(exist_ok=True)

    def setUp(self):
        super().setUp()
        OGLInitialize()
        self._preferences: UmlPreferences = UmlPreferences()

    def tearDown(self):
        super().tearDown()

    def testEmptyProject(self):

        umlShapesToXml:     UmlShapesToXml = UmlShapesToXml(projectFileName=Path(''), projectCodePath=Path('/users/hasii'))
        actualEmptyProject: str            = umlShapesToXml.xml

        self.logger.debug(f'{actualEmptyProject=}')
        self.assertEqual(EXPECTED_EMPTY_PROJECT, actualEmptyProject, 'Empty project changed')

    def testEmptyDiagram(self):

        umlShapesToXml: UmlShapesToXml = UmlShapesToXml(projectFileName=Path(''), projectCodePath=Path('/users/hasii'))
        emptyDiagram:   UmlDocument     = UmlDocument()

        umlShapesToXml.serialize(umlDiagram=emptyDiagram)

        actualEmptyDiagram: str = umlShapesToXml.xml

        self.logger.debug(f'{actualEmptyDiagram=}')
        self.assertEqual(EXPECTED_EMPTY_DIAGRAM, actualEmptyDiagram, 'Empty diagram changed')

    def testSingleUmlClass(self):

        umlShapesToXml:     UmlShapesToXml = self._createXmlCreator()
        singleClassDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.CLASS_DOCUMENT, 'Unit Test Class Diagram')
        singleClass:        UmlClass       = self._createSingleClass()

        singleClass.id = 'play.small.long.group'        # So XML matches
        singleClass.modelClass.id   = '0'
        singleClass.modelClass.name = 'ClassName1'

        singleClassDiagram.umlClasses.append(singleClass)
        umlShapesToXml.serialize(umlDiagram=singleClassDiagram)

        singleClassXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleClassXML=}')
        self._debugWriteToFile('SingleClass.xml', xml=singleClassXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_CLASS_XML, singleClassXML, 'Class serialization changed')

    def testSingleUseCase(self):
        umlShapesToXml:       UmlShapesToXml = self._createXmlCreator()
        singleUseCaseDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.USE_CASE_DOCUMENT, 'Use Case Diagram')

        useCase: UseCase = UseCase(name='I am a lonely boy')
        useCase.id = '1'
        umlUseCase:  UmlUseCase  = UmlUseCase(
            useCase=useCase,
            size=UmlDimensions(width=125, height=100)
        )
        umlUseCase.id = 'remember.central.issue.child'      # So XML matches

        umlUseCase.position = UmlPosition(x=300, y=500)

        singleUseCaseDiagram.umlUseCases.append(umlUseCase)
        umlShapesToXml.serialize(umlDiagram=singleUseCaseDiagram)

        singleUseCaseXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleUseCaseXML=}')
        self._debugWriteToFile('SingleUseCase.xml', xml=singleUseCaseXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_USE_CASE_XML, singleUseCaseXML, 'Use Case serialization changed')

    def testSingleActor(self):
        umlShapesToXml:     UmlShapesToXml = self._createXmlCreator()
        singleActorDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.USE_CASE_DOCUMENT, 'Use Case Actor Diagram')

        actor: Actor = Actor(actorName='LoboMalo')
        actor.id = '0'
        umlActor: UmlActor  = UmlActor(
            actor=actor,
            size=UmlDimensions(width=233, height=233)
        )
        umlActor.id       = 'remember.central.issue.child'
        umlActor.position = UmlPosition(x=500, y=200)

        singleActorDiagram.umlActors.append(umlActor)

        umlShapesToXml.serialize(singleActorDiagram)

        singleActorXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleActorXML=}')
        self._debugWriteToFile('SingleActor.xml', xml=singleActorXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_ACTOR, singleActorXML, 'Actor serialization changed')

    def testSingleNote(self):

        umlShapesToXml:    UmlShapesToXml = self._createXmlCreator()
        singleNoteDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.USE_CASE_DOCUMENT, 'Uml Note Diagram')

        note: Note = Note(content='I am the best MAGA Note')
        note.id = '777'

        umlNote: UmlNote = UmlNote(
            note=note,
            size=UmlDimensions(width=233, height=233)
        )
        umlNote.id       = 'remember.the.Alamo'
        umlNote.position = UmlPosition(x=666, y=777)

        singleNoteDiagram.umlNotes.append(umlNote)
        umlShapesToXml.serialize(umlDiagram=singleNoteDiagram)

        singleNoteXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleNoteXML=}')
        self._debugWriteToFile('SingleNote.xml', xml=singleNoteXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_NOTE, singleNoteXML, 'Note serialization changed')

    def testSingleText(self):

        umlShapesToXml:    UmlShapesToXml = self._createXmlCreator()
        singleTextDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.CLASS_DOCUMENT, 'Uml Text Diagram')

        text: Text = Text(content='Soy el mejor texto americano')
        text.id = '1789'

        umlText: UmlText = UmlText(
            text=text,
            size=UmlDimensions(width=150, height=50)
        )

        umlText.id       = 'remember.the.Alamo'
        umlText.position = UmlPosition(x=1024, y=768)

        singleTextDiagram.umlTexts.append(umlText)
        umlShapesToXml.serialize(umlDiagram=singleTextDiagram)

        singleTextXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleTextXML=}')
        self._debugWriteToFile('SingleText.xml', xml=singleTextXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_TEXT, singleTextXML, 'Note serialization changed')

    def testComplexClass(self):

        umlShapesToXml:       UmlShapesToXml = self._createXmlCreator()
        multipleClassDiagram: UmlDocument     = self._createUmlDiagram(UmlDocumentType.CLASS_DOCUMENT, 'Complex Class Diagram')

        classOne: UmlClass = self._createSingleClass(size=UmlDimensions(75, 75),   position=UmlPosition(333, 333))
        classTwo: UmlClass = self._createSingleClass(size=UmlDimensions(200, 100), position=UmlPosition(666, 666))

        classOne.modelClass.addMethod(self._createSingleMethod())
        classOne.modelClass.addMethod(self._createSingleMethod())

        classTwo.modelClass.addMethod(self._createSingleMethod())
        classTwo.modelClass.addMethod(self._createSingleMethod())

        classOne.modelClass.addField(self._createSingleField())
        classOne.modelClass.addField(self._createSingleField())

        classTwo.modelClass.addField(self._createSingleField())
        classTwo.modelClass.addField(self._createSingleField())

        displayParameterChoices: List[DisplayParameters] = [
            DisplayParameters.DO_NOT_DISPLAY_PARAMETERS,
            DisplayParameters.DISPLAY_PARAMETERS,
            DisplayParameters.UNSPECIFIED
        ]
        classOne.modelClass.displayParameters = choice(displayParameterChoices)
        classTwo.modelClass.displayParameters = choice(displayParameterChoices)
        self.logger.debug(f'{classOne.modelClass.displayParameters=}')
        self.logger.debug(f'{classTwo.modelClass.displayParameters=}')

        multipleClassDiagram.umlClasses.append(classOne)
        multipleClassDiagram.umlClasses.append(classTwo)

        umlShapesToXml.serialize(umlDiagram=multipleClassDiagram)

        multipleClassXML: str = umlShapesToXml.xml

        self.logger.debug(f'{multipleClassXML=}')

        self._debugWriteToFile('MultipleClassXML.xml', xml=multipleClassXML)

    def _createSingleClass(self, size: UmlDimensions = UmlDimensions(width=125, height=100), position: UmlPosition = UmlPosition(x=300, y=500)) -> UmlClass:
        """

        Args:
            size:
            position:

        Returns:
        """

        umlClass: UmlClass = UmlClass(
            modelClass=self._createModelClass(),
            size=size
        )

        umlClass.position = position
        return umlClass

    def _createModelClass(self) -> Class:

        className: str = f'{self._preferences.defaultClassName}{TestUmlShapesToXml.classCounter}'
        TestUmlShapesToXml.classCounter += 1

        modelClass: Class  = Class(name=className)
        modelClass.stereotype  = Stereotype.METACLASS
        modelClass.showFields  = True
        modelClass.showMethods = True
        modelClass.displayParameters = DisplayParameters.UNSPECIFIED

        return modelClass

    def _createSingleMethod(self) -> Method:

        methodName: str = f'{self._preferences.defaultNameMethod}-{TestUmlShapesToXml.methodCounter}'
        TestUmlShapesToXml.methodCounter += 1
        method: Method = Method(name=methodName)

        parameter: Parameter = self._createSingleParameter()
        method.addParameter(parameter)

        return method

    def _createSingleField(self) -> Field:

        fieldName: str = f'{self._preferences.defaultNameField}-{TestUmlShapesToXml.fieldCounter}'
        TestUmlShapesToXml.fieldCounter += 1

        field:  Field            = Field(name=fieldName)
        visibility: List[Visibility] = [Visibility.PRIVATE, Visibility.PROTECTED, Visibility.PUBLIC]

        field.visibility = choice(visibility)

        return field

    def _createSingleParameter(self) -> Parameter:

        parameterName: str = f'{self._preferences.defaultNameParameter}-{TestUmlShapesToXml.parameterCounter}'
        TestUmlShapesToXml.parameterCounter += 1

        parameter: Parameter  = Parameter(name=parameterName)
        typeList:      List[ParameterType] = [ParameterType(value='str'), ParameterType(value='float'), ParameterType(value='int')]

        parameter.type = choice(typeList)
        self.logger.debug(f'{parameter.type=}')

        return parameter

    def _createXmlCreator(self) -> UmlShapesToXml:

        umlShapesToXml: UmlShapesToXml = UmlShapesToXml(projectFileName=Path(''), projectCodePath=Path('/users/hasii'))
        return umlShapesToXml

    def _debugWriteToFile(self, fileName: str, xml: str):

        p: Path = Path(f'/{TestUmlShapesToXml.TEMPORARY_PATH}/{fileName}')
        # p: Path = Path(f'/tmp/{fileName}')

        p.write_text(xml)

    @classmethod
    def deleteDirectory(cls, path: Path):
        """
        Will delete any files in the directory or subdirectories

        Args:
            path: The directory to delete

        """
        for posixPath in path.iterdir():
            if posixPath.is_dir():
                cls.deleteDirectory(posixPath)
            else:
                posixPath.unlink()
        path.rmdir()  # Remove the directory itself


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUmlShapesToXml))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
