from typing import List
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from tests.demo.eventengine.DemoAppPubSubEngine import DemoAppPubSubEngine
from tests.demo.eventengine.DemoMessageType import DemoMessageType
from tests.demo.eventengine.IAppPubSubEngine import UniqueId

UNIQUE_ID: UniqueId = UniqueId('DEADBEEF')


class TestDemoAppPubSubEngine(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 21 July 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testDiagramChanged(self):

        eventEngine: DemoAppPubSubEngine = DemoAppPubSubEngine()
        eventEngine.subscribe(DemoMessageType.DIAGRAM_SELECTION_CHANGED, uniqueId=UNIQUE_ID, callback=self._diagramChangedCallback)

        eventEngine.sendMessage(DemoMessageType.DIAGRAM_SELECTION_CHANGED, uniqueId=UNIQUE_ID, name='Bogus', data=[1, 2, 3])

    def _diagramChangedCallback(self, name: str, data: List[int]):
        self.logger.debug(f'{name}, {data}')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestDemoAppPubSubEngine))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
