
from unittest import TestSuite
from unittest import main as unitTestMain

from pathlib import Path

from codeallyadvanced.ui.UnitTestBaseW import UnitTestBaseW
from pyutmodelv2.PyutActor import PyutActor

from pyutmodelv2.PyutClass import PyutClass
from pyutmodelv2.PyutUseCase import PyutUseCase
from pyutmodelv2.enumerations.PyutDisplayParameters import PyutDisplayParameters
from pyutmodelv2.enumerations.PyutStereotype import PyutStereotype

from umlshapes.preferences.UmlPreferences import UmlPreferences
from umlshapes.shapes.UmlActor import UmlActor

from umlshapes.shapes.UmlClass import UmlClass
from umlshapes.shapes.UmlUseCase import UmlUseCase
from umlshapes.types.UmlDimensions import UmlDimensions
from umlshapes.types.UmlPosition import UmlPosition

from wx.lib.ogl import OGLInitialize

from umlio.IOTypes import UmlDiagram
from umlio.IOTypes import UmlDiagramTitle
from umlio.IOTypes import UmlDiagramType

from umlio.UmlShapesToXml import UmlShapesToXml

EXPECTED_EMPTY_PROJECT: str = '<?xml version=\'1.0\' encoding=\'iso-8859-1\'?>\n<UmlProject version="12.0" codePath="/users/hasii" />'

EXPECTED_EMPTY_DIAGRAM: str = (
    '<?xml version=\'1.0\' encoding=\'iso-8859-1\'?>\n'
    '<UmlProject version="12.0" codePath="/users/hasii">\n    '
    '<UMLDiagram type="Not Set" title="" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1" />\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_CLASS_XML: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject version="12.0" codePath="/users/hasii">\n'
    '    <UMLDiagram type="Class Diagram" title="Unit Test Class Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlClass id="play.small.long.group" width="125" height="100" x="300" y="500">\n'
    '            <PyutClass id="0" name="ClassName 1" displayMethods="True" displayParameters="Unspecified" displayConstructor="Unspecified" displayDunderMethods="Unspecified" displayFields="True" displayStereotype="True" fileName="" description="" />\n'
    '        </UmlClass>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_USE_CASE_XML: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject version="12.0" codePath="/users/hasii">\n'
    '    <UMLDiagram type="Use Case Diagram" title="Use Case Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlUseCase id="remember.central.issue.child" width="125" height="100" x="300" y="500">\n'
    '            <PyutUseCase id="1" name="I am a lonely boy" fileName="" />\n'
    '        </UmlUseCase>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)

EXPECTED_SINGLE_ACTOR: str = (
    "<?xml version='1.0' encoding='iso-8859-1'?>\n"
    '<UmlProject version="12.0" codePath="/users/hasii">\n'
    '    <UMLDiagram type="Use Case Diagram" title="Use Case Actor Diagram" scrollPositionX="1" scrollPositionY="1" pixelsPerUnitX="1" pixelsPerUnitY="1">\n'
    '        <UmlActor id="remember.central.issue.child" width="233" height="233" x="500" y="200">\n'
    '            <PyutActor id="0" name="LoboMalo" fileName="" />\n'
    '        </UmlActor>\n'
    '    </UMLDiagram>\n'
    '</UmlProject>'
)


class TestUmlShapesToXml(UnitTestBaseW):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 19 June 2025
    """

    classCounter: int = 1

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()
        OGLInitialize()
        self._preferences: UmlPreferences = UmlPreferences()

    def tearDown(self):
        super().tearDown()

    def testEmptyProject(self):

        umlShapesToXml:     UmlShapesToXml = UmlShapesToXml(projectCodePath=Path('/users/hasii'))
        actualEmptyProject: str            = umlShapesToXml.xml

        self.logger.debug(f'{actualEmptyProject=}')
        self.assertEqual(EXPECTED_EMPTY_PROJECT, actualEmptyProject, 'Empty project changed')

    def testEmptyDiagram(self):

        umlShapesToXml: UmlShapesToXml = UmlShapesToXml(projectCodePath=Path('/users/hasii'))
        emptyDiagram:   UmlDiagram     = UmlDiagram()

        umlShapesToXml.serialize(umlDiagram=emptyDiagram)

        actualEmptyDiagram: str = umlShapesToXml.xml

        self.logger.debug(f'{actualEmptyDiagram=}')
        self.assertEqual(EXPECTED_EMPTY_DIAGRAM, actualEmptyDiagram, 'Empty diagram changed')

    def testSingleUmlClass(self):

        umlShapesToXml:     UmlShapesToXml = self._createXmlCreator()
        singleClassDiagram: UmlDiagram     = self._createUmlDiagram(UmlDiagramType.CLASS_DIAGRAM, 'Unit Test Class Diagram')
        singleClass:        UmlClass       = self._createSingleClass()

        singleClass.id = 'play.small.long.group'        # So XML matches
        singleClass.id = 'play.small.long.group'        # So XML matches
        singleClass.pyutClass.id = 0

        singleClassDiagram.umlClasses.append(singleClass)
        umlShapesToXml.serialize(umlDiagram=singleClassDiagram)

        singleClassXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleClassXML=}')
        self._debugWriteToFile('SingleClass.xml', xml=singleClassXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_CLASS_XML, singleClassXML, 'Class serialization changed')

    def testSingleUseCase(self):
        umlShapesToXml:       UmlShapesToXml = self._createXmlCreator()
        singleUseCaseDiagram: UmlDiagram     = self._createUmlDiagram(UmlDiagramType.USE_CASE_DIAGRAM, 'Use Case Diagram')

        pyutUseCase: PyutUseCase = PyutUseCase(name='I am a lonely boy')
        pyutUseCase.id = 1
        umlUseCase:  UmlUseCase  = UmlUseCase(
            pyutUseCase=pyutUseCase,
            size=UmlDimensions(width=125, height=100)
        )
        umlUseCase.id = 'remember.central.issue.child'      # So XML matches

        umlUseCase.position = UmlPosition(x=300, y=500)

        singleUseCaseDiagram.umlUseCases.append(umlUseCase)
        umlShapesToXml.serialize(umlDiagram=singleUseCaseDiagram)

        singleUseCaseXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleUseCaseXML=}')
        self._debugWriteToFile('SingleUseCase.xml', xml=singleUseCaseXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_USE_CASE_XML, singleUseCaseXML, 'Use Case serialization changed')

    def testSingleActor(self):
        umlShapesToXml:     UmlShapesToXml = self._createXmlCreator()
        singleActorDiagram: UmlDiagram     = self._createUmlDiagram(UmlDiagramType.USE_CASE_DIAGRAM, 'Use Case Actor Diagram')

        pyutActor: PyutActor = PyutActor(actorName='LoboMalo')
        pyutActor.id = 0
        umlActor:  UmlActor  = UmlActor(
            pyutActor=pyutActor,
            size=UmlDimensions(width=233, height=233)
        )
        umlActor.id = 'remember.central.issue.child'
        umlActor.position = UmlPosition(x=500, y=200)

        singleActorDiagram.umlActors.append(umlActor)

        umlShapesToXml.serialize(singleActorDiagram)

        singleActorXML: str = umlShapesToXml.xml

        self.logger.debug(f'{singleActorXML=}')
        self._debugWriteToFile('SingleActor.xml', xml=singleActorXML)

        self.maxDiff = None
        self.assertEqual(EXPECTED_SINGLE_ACTOR, singleActorXML, 'Actor serialization changed')

    def _createSingleClass(self) -> UmlClass:

        umlClass: UmlClass = UmlClass(
            pyutClass=self._createPyutClass(),
            size=UmlDimensions(width=125, height=100)
        )

        umlClass.position = UmlPosition(x=300, y=500)
        return umlClass

    def _createPyutClass(self) -> PyutClass:

        className: str = f'{self._preferences.defaultClassName} {TestUmlShapesToXml.classCounter}'
        TestUmlShapesToXml.classCounter += 1

        pyutClass: PyutClass  = PyutClass(name=className)
        pyutClass.stereotype  = PyutStereotype.METACLASS
        pyutClass.showFields  = True
        pyutClass.showMethods = True
        pyutClass.displayParameters = PyutDisplayParameters.UNSPECIFIED

        return pyutClass

    def _createXmlCreator(self) -> UmlShapesToXml:

        umlShapesToXml: UmlShapesToXml = UmlShapesToXml(projectCodePath=Path('/users/hasii'))
        return umlShapesToXml

    def _createUmlDiagram(self, diagramType: UmlDiagramType, diagramTitle: str) -> UmlDiagram:

        umlDiagram: UmlDiagram  = UmlDiagram()
        umlDiagram.diagramType  = diagramType
        umlDiagram.diagramTitle = UmlDiagramTitle(diagramTitle)

        return umlDiagram

    def _debugWriteToFile(self, fileName: str, xml: str):

        p: Path = Path(f'/tmp/{fileName}')

        p.write_text(xml)


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestUmlShapesToXml))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
