
from unittest import TestSuite
from unittest import main as unitTestMain

from pathlib import Path

from codeallybasic.UnitTestBase import UnitTestBase

from umlio.IOTypes import UmlDocument
from umlio.IOTypes import UmlDocumentTitle
from umlio.IOTypes import UmlDocumentType
from umlio.IOTypes import UmlProject
from umlio.Writer import Writer

from tests.umlio.UmlIOBaseTest import UmlIOBaseTest
from tests.umlio.UmlIOBaseTest import EMPTY_DIAGRAMS_COMPRESSED_PROJECT
from tests.umlio.UmlIOBaseTest import EMPTY_DIAGRAMS_XML_PROJECT

UNIT_TEST_DIAGRAM_DIRECTORY:       str = 'UmlDiagramProjects'

EXPECTED_FILE_SIZE: int = 258


class TestWriter(UmlIOBaseTest):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 06 July 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testWriteEmptyDiagramsXmlFile(self):

        directory:             Path = Path.home() / UNIT_TEST_DIAGRAM_DIRECTORY
        emptyDiagramsFileName: Path = directory / EMPTY_DIAGRAMS_XML_PROJECT

        umlProject: UmlProject = self._createEmptyDiagramsProject(emptyDiagramsFileName)
        directory.mkdir(parents=True, exist_ok=True)
        emptyDiagramsFileName.touch()
        writer: Writer = Writer()
        writer.writeXmlFile(umlProject=umlProject, fileName=emptyDiagramsFileName)

        goldenFileName: str = UnitTestBase.getFullyQualifiedResourceFileName(
            package=UmlIOBaseTest.GOLDEN_FILES_PACKAGE_NAME,
            fileName=EMPTY_DIAGRAMS_XML_PROJECT
        )
        status: int = self._runDiff(generatedFile=emptyDiagramsFileName, goldenFile=Path(goldenFileName))

        self.assertEqual(0, status)

    def testWriteEmptyDiagramsCompressedFile(self):
        directory:             Path = Path.home() / UNIT_TEST_DIAGRAM_DIRECTORY
        emptyDiagramsFileName: Path = directory / EMPTY_DIAGRAMS_COMPRESSED_PROJECT

        umlProject: UmlProject = self._createEmptyDiagramsProject(emptyDiagramsFileName)
        directory.mkdir(parents=True, exist_ok=True)
        emptyDiagramsFileName.touch()

        writer: Writer = Writer()
        writer.writeFile(umlProject=umlProject, fileName=emptyDiagramsFileName)

        actualFileSize: int = emptyDiagramsFileName.stat().st_size

        # self.assertEqual(EXPECTED_FILE_SIZE, actualFileSize, 'Hmm.  Maybe zlib changed')
        self.assertGreater(actualFileSize, 0, 'Looks like it is empty')

    def _createEmptyDiagramsProject(self, emptyDiagramsFileName: Path) -> UmlProject:

        umlProject: UmlProject = UmlProject()
        umlProject.codePath = Path.home()
        umlProject.fileName = Path(emptyDiagramsFileName.as_posix())

        titleZero: UmlDocumentTitle = UmlDocumentTitle('Number Zero')
        titleOne:  UmlDocumentTitle = UmlDocumentTitle('Number One')
        titleTwo:  UmlDocumentTitle = UmlDocumentTitle('Number Two')

        diagramZero: UmlDocument = self._createUmlDiagram(diagramType=UmlDocumentType.CLASS_DOCUMENT, diagramTitle=titleZero)
        diagramOne:  UmlDocument = self._createUmlDiagram(diagramType=UmlDocumentType.USE_CASE_DOCUMENT, diagramTitle=titleOne)
        diagramTwo:  UmlDocument = self._createUmlDiagram(diagramType=UmlDocumentType.SEQUENCE_DOCUMENT, diagramTitle=titleTwo)

        umlProject.umlDocuments[titleZero] = diagramZero
        umlProject.umlDocuments[titleOne]  = diagramOne
        umlProject.umlDocuments[titleTwo]  = diagramTwo

        return umlProject


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestWriter))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
