from pathlib import Path
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from tests.umlio.UmlIOBaseTest import EMPTY_DIAGRAMS_XML_PROJECT
from tests.umlio.UmlIOBaseTest import UmlIOBaseTest
from umlio.Reader import Reader


class TestReader(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 11 July 2025
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testBasicXmlRead(self):

        emptyProject: str = UnitTestBase.getFullyQualifiedResourceFileName(
            package=UmlIOBaseTest.GOLDEN_FILES_PACKAGE_NAME,
            fileName=EMPTY_DIAGRAMS_XML_PROJECT)

        reader: Reader = Reader()

        reader.readXmlFile(Path(emptyProject))


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestReader))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
