
from typing import cast

from pathlib import Path

from umlshapes.lib.ogl import OGLInitialize

from umlmodel.Class import Class
from umlmodel.Class import ClassIndex
from umlmodel.Link import Links
from umlmodel.ModelTypes import ClassName

from umlshapes.shapes.UmlClass import UmlClass

from umlio.IOTypes import UmlClasses
from umlio.IOTypes import UmlDocument
from umlio.IOTypes import UmlDocumentTitle
from umlio.IOTypes import UmlProject

from umlio.IOTypes import UmlLinks as IOUmlLinks

from umlio.Reader import Reader

from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase
from codeallyadvanced.ui.UnitTestBaseW import UnitTestBaseW


MULTI_LINK_XML_PROJECT:           str = 'LinkModelRationalization.xml'
FDL_ASSOCIATION_LINK_XML_PROJECT: str = 'FDLAssociationLink.xml'
FDL_INTERFACE_LINK_XML_PROJECT:   str = 'FDLInterfaceLink.xml'

class TestLinkDataModelRationalization(UnitTestBaseW):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 23 March 2026
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()
        OGLInitialize()

    def tearDown(self):
        super().tearDown()

    def testGoodInheritanceLinkDataModel(self):

        linkDataModelProject: str = UnitTestBase.getFullyQualifiedResourceFileName(
            package=UnitTestBase.RESOURCES_PACKAGE_NAME,
            fileName=MULTI_LINK_XML_PROJECT)

        reader: Reader = Reader()

        umlProject: UmlProject = reader.readXmlFile(Path(linkDataModelProject))

        multiLinkDiagram: UmlDocument = umlProject.umlDocuments[UmlDocumentTitle('MultiLink Diagram')]

        umlLinks: IOUmlLinks = multiLinkDiagram.umlLinks
        self.assertEqual(6, len(umlLinks), 'Not the correct # of links')   # noqa

        umlClasses: UmlClasses = multiLinkDiagram.umlClasses

        modelClassIndex:  ClassIndex = ClassIndex({})
        for umlClass in umlClasses:

            modelClass: Class = cast(UmlClass, umlClass).modelClass
            modelClassIndex[ClassName(modelClass.name)] = modelClass

        basePasteCommand:    Class = modelClassIndex[ClassName('BasePasteCommand')]
        useCasePasteCommand: Class = modelClassIndex[ClassName('UseCasePasteCommand')]
        actorPasteCommand:   Class = modelClassIndex[ClassName('ActorPasteCommand')]
        classPasteCommand:   Class = modelClassIndex[ClassName('ClassPasteCommand')]
        baseCommand:         Class = modelClassIndex[ClassName('BaseCommand')]
        baseCutCommand:      Class = modelClassIndex[ClassName('BaseCutCommand')]

        self.assertIn(basePasteCommand, useCasePasteCommand.parents)
        self.assertIn(basePasteCommand, actorPasteCommand.parents)
        self.assertIn(basePasteCommand, classPasteCommand.parents)

        self.assertIn(baseCommand, basePasteCommand.parents)
        self.assertIn(baseCommand, baseCutCommand.parents)

    def testGoodAssociationLinkDataModel(self):

        linkDataModelProject: str = UnitTestBase.getFullyQualifiedResourceFileName(
            package=UnitTestBase.RESOURCES_PACKAGE_NAME,
            fileName=FDL_ASSOCIATION_LINK_XML_PROJECT)

        reader: Reader = Reader()
        umlProject: UmlProject = reader.readXmlFile(Path(linkDataModelProject))

        associationLinksDiagram: UmlDocument = umlProject.umlDocuments[UmlDocumentTitle('AssociationLinks')]

        umlLinks: IOUmlLinks = associationLinksDiagram.umlLinks

        self.assertEqual(3, len(umlLinks), 'Not the correct # of links')   # noqa

        umlClasses: UmlClasses = associationLinksDiagram.umlClasses

        modelClassIndex:  ClassIndex = ClassIndex({})
        for umlClass in umlClasses:

            modelClass: Class = cast(UmlClass, umlClass).modelClass
            modelClassIndex[ClassName(modelClass.name)] = modelClass

        self.logger.debug(f'{modelClassIndex=}')
        aggregatorModel: Class = modelClassIndex[ClassName('Aggregator')]

        links: Links = aggregatorModel.links
        self.assertIs(3, len(links),  'Link count mismatch')           # noqa

        aggregatedModelClasses = list(modelClassIndex.values())
        aggregatedModelClasses.remove(aggregatorModel)

        for modelLink in links:
            self.assertEqual(aggregatorModel, modelLink.source, 'I should be the source')
            self.assertIn(modelLink.destination, aggregatedModelClasses, 'Should be one of these')

    def testGoodInterfaceLinkDataModel(self):

        linkDataModelProject: str = UnitTestBase.getFullyQualifiedResourceFileName(
            package=UnitTestBase.RESOURCES_PACKAGE_NAME,
            fileName=FDL_INTERFACE_LINK_XML_PROJECT)

        reader: Reader = Reader()
        umlProject: UmlProject = reader.readXmlFile(Path(linkDataModelProject))

        interfaceLinksDiagram: UmlDocument = umlProject.umlDocuments[UmlDocumentTitle('Interface Diagram')]

        umlLinks: IOUmlLinks = interfaceLinksDiagram.umlLinks
        self.assertEqual(3, len(umlLinks), 'Not the correct # of links')   # noqa

        umlClasses: UmlClasses = interfaceLinksDiagram.umlClasses

        modelClassIndex:  ClassIndex = ClassIndex({})
        for umlClass in umlClasses:

            modelClass: Class = cast(UmlClass, umlClass).modelClass
            modelClassIndex[ClassName(modelClass.name)] = modelClass

        self.logger.debug(f'{modelClassIndex=}')
        iInterfaceClass:  Class = modelClassIndex[ClassName('IInterface')]
        implementorOne:   Class = modelClassIndex[ClassName('ImplementorOne')]
        implementorTwo:   Class = modelClassIndex[ClassName('ImplementorTwo')]
        implementorThree: Class = modelClassIndex[ClassName('ImplementorThree')]

        self.assertIn(iInterfaceClass, implementorOne.parents)
        self.assertIn(iInterfaceClass, implementorTwo.parents)
        self.assertIn(iInterfaceClass, implementorThree.parents)

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestLinkDataModelRationalization))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
